# fly.toml app configuration file generated for botlita on 2023-06-06T14:57:08+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "botlita"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
